# Generated by Django 2.1.5 on 2019-02-17 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position', '0003_ptposition'),
        ('base', '0001_initial'),
        ('factorbuy', '0005_auto_20190214_1054'),
        ('factorsell', '0005_factorsellnday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.CharField(max_length=64, verbose_name='买入日期')),
                ('buy_price', models.CharField(max_length=64, verbose_name='买入价格')),
                ('buy_cnt', models.CharField(max_length=64, verbose_name='买入数量')),
                ('buy_factor', models.CharField(max_length=64, verbose_name='买入策略')),
                ('symbol', models.CharField(max_length=64, verbose_name='股票编号')),
                ('buy_pos', models.CharField(max_length=64, verbose_name='买入滑dian')),
                ('buy_type_str', models.CharField(max_length=64, verbose_name='买入类型')),
                ('expect_direction', models.CharField(max_length=64, verbose_name='预期方向')),
                ('sell_type_extra', models.CharField(max_length=64, verbose_name='卖出策略')),
                ('sell_date', models.CharField(max_length=64, verbose_name='卖出日期')),
                ('sell_price', models.CharField(max_length=64, verbose_name='卖出价格')),
                ('sell_type', models.CharField(max_length=64, verbose_name='卖出类型')),
                ('ml_features', models.CharField(blank=True, max_length=64, null=True, verbose_name='MLI特征')),
                ('key', models.CharField(max_length=64, verbose_name='关键字')),
                ('profit', models.CharField(max_length=64, verbose_name='盈利')),
                ('result', models.CharField(max_length=64, verbose_name='结果')),
                ('profit_cg', models.CharField(max_length=64, verbose_name='盈利比')),
                ('profit_cg_hunder', models.CharField(max_length=64, verbose_name='盈利率')),
                ('keep_days', models.CharField(max_length=64, verbose_name='持股天数')),
            ],
            options={
                'verbose_name': '回测订单',
                'verbose_name_plural': '回测订单',
            },
        ),
        migrations.CreateModel(
            name='RunLoopGroup',
            fields=[
                ('runbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.RunBase')),
                ('factor_buys', models.ManyToManyField(related_name='factor_buy_groups', to='factorbuy.FactorBuy', verbose_name='买策略组合')),
                ('factor_sells', models.ManyToManyField(related_name='factor_sell_groups', to='factorsell.FactorSell', verbose_name='卖策略组合')),
                ('positions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='position.Position', verbose_name='仓位管理')),
            ],
            options={
                'verbose_name': '回测',
                'verbose_name_plural': '回测',
            },
            bases=('base.runbase',),
        ),
        migrations.AddField(
            model_name='orders',
            name='run_loop_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='runloop.RunLoopGroup', verbose_name='回测'),
        ),
        migrations.AddField(
            model_name='orders',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Stock', verbose_name='股票'),
        ),
    ]
