# Generated by Django 2.1.5 on 2019-01-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('runloop', '0002_auto_20190113_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='runloopgroup',
            name='stocks',
            field=models.ManyToManyField(related_name='stock_groups', to='base.Stock', verbose_name='股票组合'),
        ),
    ]
