# Generated by Django 2.1.4 on 2019-02-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('factor_name', models.CharField(editable=False, max_length=64, verbose_name='策略名称')),
                ('class_name', models.CharField(editable=False, max_length=256, verbose_name='策略')),
            ],
            options={
                'verbose_name': '卖策略',
                'verbose_name_plural': '卖策略',
            },
        ),
        migrations.CreateModel(
            name='FactorSellBreakXd',
            fields=[
                ('factorsell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factorsell.FactorSell')),
                ('xd', models.CharField(max_length=64, verbose_name='周期')),
            ],
            options={
                'verbose_name': '海龟卖出',
                'verbose_name_plural': '海龟卖出',
            },
            bases=('factorsell.factorsell',),
        ),
        migrations.CreateModel(
            name='FactorSellDoubleMa',
            fields=[
                ('factorsell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factorsell.FactorSell')),
                ('slow_int', models.IntegerField(verbose_name='慢线')),
                ('fast_int', models.IntegerField(verbose_name='快线')),
            ],
            options={
                'verbose_name': '双均线卖',
                'verbose_name_plural': '双均线卖',
            },
            bases=('factorsell.factorsell',),
        ),
    ]
