# Generated by Django 2.1.4 on 2019-02-13 09:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factorsell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorSellAtrNStop',
            fields=[
                ('factorsell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factorsell.FactorSell')),
                ('stop_loss_n', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)], verbose_name='止损(stop_loss_n乘以当日atr大于买价减close->止损)')),
                ('stop_win_n', models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)], verbose_name='止盈(stop_win_n乘以当日atr小于close减买价->止盈)')),
            ],
            options={
                'verbose_name': '止盈止损',
                'verbose_name_plural': '止盈止损',
            },
            bases=('factorsell.factorsell',),
        ),
    ]
