# Generated by Django 2.1.4 on 2019-02-13 09:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factorsell', '0002_factorsellatrnstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorSellCloseAtrN',
            fields=[
                ('factorsell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factorsell.FactorSell')),
                ('close_atr_n', models.FloatField(default=1.5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)], verbose_name='止盈(收益下跌超过close_atr_n乘以当日atr->保护止盈)')),
            ],
            options={
                'verbose_name': '保护止盈',
                'verbose_name_plural': '保护止盈',
            },
            bases=('factorsell.factorsell',),
        ),
    ]
