# Generated by Django 2.1.4 on 2019-02-13 09:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factorsell', '0003_factorsellcloseatrn'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorSellPreAtrNStop',
            fields=[
                ('factorsell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factorsell.FactorSell')),
                ('pre_atr_n', models.FloatField(default=1.5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)], verbose_name='止损(当今天价格开始剧烈下跌，采取果断平仓措施)')),
            ],
            options={
                'verbose_name': '风险止损',
                'verbose_name_plural': '风险止损',
            },
            bases=('factorsell.factorsell',),
        ),
    ]
