# Generated by Django 2.1.4 on 2019-02-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factorsell', '0004_factorsellpreatrnstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorSellNDay',
            fields=[
                ('factorsell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factorsell.FactorSell')),
                ('sell_n', models.IntegerField(default=1, verbose_name='N天')),
                ('is_sell_today', models.BooleanField(choices=[(True, 'N天后当天卖出'), (False, 'N天后隔天卖出')], verbose_name='当天隔天')),
            ],
            options={
                'verbose_name': 'N天卖出',
                'verbose_name_plural': 'N天卖出',
            },
            bases=('factorsell.factorsell',),
        ),
    ]
