# Generated by Django 2.1.4 on 2019-01-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=64, verbose_name='名称')),
                ('symbol', models.CharField(max_length=64, verbose_name='编号')),
                ('market', models.CharField(max_length=64, verbose_name='市场')),
            ],
            options={
                'verbose_name': '股票',
                'verbose_name_plural': '股票',
            },
        ),
    ]
