# Generated by Django 2.1.5 on 2019-02-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('start', models.DateField(verbose_name='开始')),
                ('end', models.DateField(verbose_name='结束')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('status', models.CharField(blank=True, default='新建', max_length=64, verbose_name='状态')),
                ('read_cash', models.IntegerField(verbose_name='初始化资金')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=16, verbose_name='名称')),
                ('symbol', models.CharField(max_length=16, verbose_name='编号')),
                ('market', models.CharField(choices=[('SH', '沪市'), ('SZ', '深市')], max_length=16, verbose_name='市场')),
                ('asset', models.CharField(max_length=64, verbose_name='价值')),
                ('co_business', models.CharField(max_length=64, verbose_name='板块')),
                ('cc', models.CharField(max_length=64, verbose_name='市值')),
                ('amplitude', models.CharField(max_length=64, verbose_name='流通')),
                ('pe_s_d', models.CharField(max_length=64, verbose_name='pe_s_d')),
                ('co_intro', models.TextField(verbose_name='基本信息')),
                ('exchange', models.CharField(choices=[('SH', '沪市'), ('SZ', '深市')], max_length=64, verbose_name='交易所')),
                ('mv', models.CharField(max_length=64, verbose_name='总市值')),
                ('pb_d', models.CharField(max_length=64, verbose_name='pb_d')),
                ('ps_d', models.CharField(max_length=64, verbose_name='ps_d')),
                ('equity', models.CharField(max_length=64, verbose_name='equity')),
                ('industry', models.CharField(max_length=64, verbose_name='板块')),
            ],
            options={
                'verbose_name': '股票',
                'verbose_name_plural': '股票',
            },
        ),
        migrations.AddField(
            model_name='runbase',
            name='stocks',
            field=models.ManyToManyField(related_name='stock_groups', to='base.Stock', verbose_name='股票组合'),
        ),
    ]
