# Generated by Django 2.1.5 on 2019-02-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runbase',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='stock_groups', to='base.Stock', verbose_name='股票组合'),
        ),
    ]
