# Generated by Django 2.1.4 on 2019-02-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickstock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceminmaxpickstock',
            name='price_max',
            field=models.FloatField(default=50, verbose_name='最大:'),
        ),
        migrations.AlterField(
            model_name='priceminmaxpickstock',
            name='price_max_ck',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], verbose_name='使用最大阀值'),
        ),
        migrations.AlterField(
            model_name='priceminmaxpickstock',
            name='price_min_ck',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], verbose_name='使用最小阀值'),
        ),
    ]
