# Generated by Django 2.1.4 on 2019-02-14 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickstock', '0002_auto_20190214_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftDistancePickStock',
            fields=[
                ('pickstock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pickstock.PickStock')),
                ('threshold_sd', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='阀值:')),
                ('min', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='范围-小:')),
                ('max', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='范围-大:')),
            ],
            options={
                'verbose_name': '位移路程',
                'verbose_name_plural': '位移路程',
            },
            bases=('pickstock.pickstock',),
        ),
        migrations.AlterField(
            model_name='priceminmaxpickstock',
            name='price_max_ck',
            field=models.BooleanField(choices=[(True, '否'), (False, '是')], verbose_name='使用最大阀值'),
        ),
        migrations.AlterField(
            model_name='priceminmaxpickstock',
            name='price_min_ck',
            field=models.BooleanField(choices=[(True, '否'), (False, '是')], verbose_name='使用最小阀值'),
        ),
    ]
