# Generated by Django 2.1.4 on 2019-02-15 08:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickstock', '0003_auto_20190214_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickStockNTopPickStock',
            fields=[
                ('pickstock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pickstock.PickStock')),
                ('n_top', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='TOP N:')),
                ('direction_top', models.IntegerField(choices=[(1, '正(涨幅)'), (-1, '负(跌幅)')], default=1, verbose_name='选取方向')),
            ],
            options={
                'verbose_name': 'top N涨跌',
                'verbose_name_plural': 'top N涨跌',
            },
            bases=('pickstock.pickstock',),
        ),
    ]
