# Generated by Django 2.1.5 on 2019-02-17 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickstock', '0004_pickstockntoppickstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickRegressAngMinMaxPickStock',
            fields=[
                ('pickstock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pickstock.PickStock')),
                ('ang_min_float', models.IntegerField(default=-5, verbose_name='最小(设定选股角度最小阀值，默认-5):')),
                ('ang_min_ck', models.BooleanField(choices=[(True, '否'), (False, '是')], verbose_name='使用最小阀值')),
                ('ang_max_float', models.IntegerField(default=5, verbose_name='最大(设定选股角度最大阀值，默认5):')),
                ('ang_max_ck', models.BooleanField(choices=[(True, '否'), (False, '是')], verbose_name='使用最大阀值')),
            ],
            options={
                'verbose_name': '角度选股',
                'verbose_name_plural': '角度选股',
            },
            bases=('pickstock.pickstock',),
        ),
    ]
