# Generated by Django 2.1.4 on 2019-02-12 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('position_name', models.CharField(editable=False, max_length=64, verbose_name='仓位策略名称')),
                ('class_name', models.CharField(editable=False, max_length=256, verbose_name='仓位策略')),
            ],
            options={
                'verbose_name': '仓位策略',
                'verbose_name_plural': '仓位策略',
            },
        ),
        migrations.CreateModel(
            name='KellyPosition',
            fields=[
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='position.Position')),
                ('win_rate', models.FloatField(verbose_name='默认kelly仓位胜率0.50')),
                ('gains_mean', models.FloatField(verbose_name='默认平均获利期望0.10')),
                ('losses_mean', models.FloatField(verbose_name='默认平均亏损期望0.05')),
            ],
            options={
                'verbose_name': 'kelly仓位管理',
                'verbose_name_plural': 'kelly仓位管理',
            },
            bases=('position.position',),
        ),
    ]
