# Generated by Django 2.1.4 on 2019-02-14 02:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtrPosPosition',
            fields=[
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='position.Position')),
                ('atr_pos_base', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(1e-05), django.core.validators.MaxValueValidator(1.0)], verbose_name='基配')),
                ('atr_base_price', models.SmallIntegerField(choices=[(12, '12 '), (13, '13 '), (14, '14 '), (15, '15 '), (16, '16 '), (17, '17 '), (18, '18 '), (19, '19 ')], default=15, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(20)], verbose_name='常价')),
            ],
            options={
                'verbose_name': 'atr资管',
                'verbose_name_plural': 'atr资管',
            },
            bases=('position.position',),
        ),
    ]
