# Generated by Django 2.1.5 on 2019-02-17 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('start', models.IntegerField(verbose_name='开始')),
                ('end', models.IntegerField(verbose_name='结束')),
                ('step', models.FloatField(verbose_name='增量')),
                ('class_name', models.CharField(choices=[('FactorSellBreakXd', '海龟卖'), ('AbuDoubleMaSell', '双均线卖')], editable=False, max_length=256, verbose_name='策略')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RangeSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('start', models.IntegerField(verbose_name='开始')),
                ('end', models.IntegerField(verbose_name='结束')),
                ('step', models.FloatField(verbose_name='增量')),
                ('class_name', models.CharField(choices=[('FactorSellBreakXd', '海龟卖'), ('AbuDoubleMaSell', '双均线卖')], editable=False, max_length=256, verbose_name='策略')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunGridSearch',
            fields=[
                ('runbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.RunBase')),
            ],
            options={
                'verbose_name': 'GridSearch',
                'verbose_name_plural': 'GridSearch',
            },
            bases=('base.runbase',),
        ),
        migrations.CreateModel(
            name='FactorBuyRangeBreakXd',
            fields=[
                ('rangebuy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gridsearch.RangeBuy')),
            ],
            options={
                'verbose_name': '海龟买入范围',
                'verbose_name_plural': '海龟买入范围',
            },
            bases=('gridsearch.rangebuy',),
        ),
        migrations.CreateModel(
            name='FactorSellRangeBreakXd',
            fields=[
                ('rangesell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gridsearch.RangeSell')),
            ],
            options={
                'verbose_name': '海龟卖出范围',
                'verbose_name_plural': '海龟卖出范围',
            },
            bases=('gridsearch.rangesell',),
        ),
        migrations.AddField(
            model_name='rungridsearch',
            name='factor_buys',
            field=models.ManyToManyField(related_name='factor_buy_groups', to='gridsearch.RangeBuy', verbose_name='买策略组合'),
        ),
        migrations.AddField(
            model_name='rungridsearch',
            name='factor_sells',
            field=models.ManyToManyField(related_name='factor_sell_groups', to='gridsearch.RangeSell', verbose_name='卖策略组合'),
        ),
    ]
