# Generated by Django 2.1.4 on 2019-02-13 07:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factorbuy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorBuyWD',
            fields=[
                ('factorbuy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factorbuy.FactorBuy')),
                ('buy_dw', models.FloatField(default=0.55, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.99)], verbose_name='胜率')),
                ('buy_dwm', models.FloatField(default=0.618, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1.0)], verbose_name='系数')),
                ('dw_period', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(120)], verbose_name='周期')),
            ],
            options={
                'verbose_name': '周涨胜率',
                'verbose_name_plural': '周涨胜率',
            },
            bases=('factorbuy.factorbuy',),
        ),
    ]
