# Generated by Django 2.1.4 on 2019-02-13 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factorbuy', '0002_factorbuywd'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekMonthBuy',
            fields=[
                ('factorbuy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factorbuy.FactorBuy')),
                ('is_buy_month_box', models.BooleanField(choices=[(True, '定期一个月'), (False, '定期一个周')], verbose_name='定期时长')),
            ],
            options={
                'verbose_name': '定期买入',
                'verbose_name_plural': '定期买入',
            },
            bases=('factorbuy.factorbuy',),
        ),
    ]
