# Generated by Django 2.1.4 on 2019-02-13 08:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factorbuy', '0003_weekmonthbuy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownUpTrend',
            fields=[
                ('factorbuy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factorbuy.FactorBuy')),
                ('xd', models.SmallIntegerField(choices=[(5, '5 天'), (10, '10 天'), (15, '15 天'), (20, '20 天'), (25, '25 天'), (30, '30 天'), (35, '35 天'), (40, '40 天'), (45, '45 天'), (50, '50 天'), (55, '55 天'), (60, '60 天'), (65, '65 天'), (70, '70 天'), (75, '75 天'), (80, '80 天'), (85, '85 天'), (90, '90 天'), (95, '95 天'), (100, '100 天'), (105, '105 天'), (110, '110 天'), (115, '115 天')], default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='短线周期')),
                ('past_factor', models.SmallIntegerField(choices=[(5, '5 '), (10, '10 '), (15, '15 '), (20, '20 '), (25, '25 '), (30, '30 '), (35, '35 '), (40, '40 '), (45, '45 '), (50, '50 '), (55, '55 '), (60, '60 '), (65, '65 '), (70, '70 '), (75, '75 '), (80, '80 '), (85, '85 '), (90, '90 '), (95, '95 '), (100, '100 '), (105, '105 '), (110, '110 '), (115, '115 ')], default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='长线乘数(长线乘数：短线基础 x 长线乘数 = 长线周期)')),
                ('down_deg_threshold', models.SmallIntegerField(choices=[(-10, '-10 '), (-9, '-9 '), (-8, '-8 '), (-7, '-7 '), (-6, '-6 '), (-5, '-5 '), (-4, '-4 '), (-3, '-3 '), (-2, '-2 '), (-1, '-1 ')], default=-3, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(0)], verbose_name='角度阀值(拟合趋势角度阀值：如-2,-3,-4)')),
            ],
            options={
                'verbose_name': '长跌短涨',
                'verbose_name_plural': '长跌短涨',
            },
            bases=('factorbuy.factorbuy',),
        ),
    ]
