# Generated by Django 2.1.4 on 2019-02-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factorbuy', '0004_downuptrend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorbuydoublema',
            name='slow_int',
            field=models.IntegerField(verbose_name='慢线'),
        ),
    ]
